### ISSUE TITLE
Invalid Token

### ISSUE THREAD

**Issue by Mat2001mat** [WowzaMediaSystems/wse-plugin-streamresolver#2]
Hi guys,

Thank you for the recent update. 

I'm not sure why it's doing this, but every time I use the updated module, it seems to break our authentication/token module. Our logs are showing that the token is being rejected on the Edge server when the new version of the module is enabled. If I connect directly to the Origin, it's fine. As soon as I revert back to an earlier version of the module. It starts to work again.

Is there any possibility it's interrupting the stream name or any parameters passed? 

Many thanks,

Matt

**Comment by Mat2001mat** [comment]
Hi guys,

Upon further investigation. It appears to be prefixing the stream name with cupertinostreamingpacketizer_

So instead of <streamname> being passed, you get cupertinostreamingpacketizer_<streamname>.

Is this something that is unavoidable? 

Many thanks,

Matt

**Comment by rogerlittin** [comment]
Hi Matt,

The stream name prefixing is required on the edges so that the each type of mediaCaster can be handled separately. When the origin URLs are resolved (resolveStreamAlias methods) there are cases where the mediaCaster type isn't know from the request so we needed to use the stream name to determine which set of origin urls we need to use.

The stream names that are prefixed are the ones used by the http repeater mediaCasters. Internally, they are prefixed with the LiveStreamPacketiser names followed by an underscore. e.g _cupertinostreamingpacketizer__ 
_sanjosestreamingpacketizer__
_mpegdashstreamingpacketizer__
_smoothstreaingpacketizer__

The players should always use the un-prefixed name. The mediaCasters used for RTMP or RTSP playback isn't prefixed.

**Comment by Mat2001mat** [comment]
Hi Roger,

Thank you for explaining the behaviour. If that's the case, then I'll just make amendments to our SecureToken module remove these from the string. 

sanjosestreamingpacketizer_
mpegdashstreamingpacketizer_
smoothstreaingpacketizer_

Honestly, I'm so grateful that you guys wrote this module. I've been looking for something like this to make our Wowza platform scale easier. 

I'm 99% complete on my project now. I've only got one more issue to work through. It seems that the Module can't detect that a stream has moved from one Origin server to another if any kind of DVR playback is being used. For RTMP/Cuptertino it works absolutely fine, but it keeps getting stuck on DVR streams.

When I look at the 8086:connectioncounts, I can see that the Stream is still active, despite the fact it's moved to another server. I think for some reason DVR streams remain open even if they aren't Live because they still can be played back and remain open.

Is there anything I can do to get past this? We only use DVR streams in our workflow :).

Thanks for continuing to develop my favourite application.

Matt

**Comment by rogerlittin** [comment]
Hi Mat,

We haven't coded the module to specifically work with dvr so it is probably using the info from the base http connections. In most cases, that would be the same which is why it sort of works.

We could probably make the module detect changes in the dvr source but I'm not sure that having dvr streams switch to a different origin is actually a good idea. It would end up breaking the dvr workflow.

So that the players can rewind the stream, the origin server is continuously recording the dvr chunks as they arrive. If the source switches to a different origin, the new origin wouldn't have the old recordings so any players wound back from live would fail if we connected the edge to the new origin and any new players would only be able to rewind back to the point where the switch occurred.

Also, as you have noted, dvr can be live or recorded. If the source stream drops, the dvr automatically switches to recorded mode and any currently connected players and any new players would automatically switch to the recorded playlist as well. The recorded playlist has an end list marker indicating that it is a recording so the players never re-request the playlist again so even if the live stream restarts, any currently connected players won't detect it unless they reconnect.

The dvr source should always connect to the same origin so that the stream remains consistent.

If the source does have to reconnect to a different origin then it should use a new stream name to make sure there isn't any unexpected playback issues. You would have to use some sort of out of band signalling to let the players know whats happening. They would reconnect to the new stream name via the edge and the edge would then connect to the new origin using the new name.

If you have any other ideas about how it could work then please let me know.

Thanks,

Roger.

**Comment by Mat2001mat** [comment]
Hi Roger,

Sorry for the late response, I've been travelling and not had a chance to catch up.

Thank you for your detailed response. This is roughly what I expected and why I'm seeing the behavior I am. For the most part, I think we can get around the DVR shifting issue by ensuring our load balancer maintains a persistant connection to the same origin server. That way, it should remain there unless the server fails.

We have a slightly different work from from some. We take lots of video streams, up to maybe 200+ a day, and distribute them to a few users each. Rather than few to many. So I'm attempting to build a very durable and scalable load balanced environment that can deal with a lot of incoming streams. 

As standard, we provide DVR playback as the main playlist and only offer a small 1 hour window. We run video streams for hours upon hours and found that keeping longer windows eventually caused large playlist issues. 

My only main concern is if for some reason a stream got started on one origin server, then reconnected again onto a new Origin. We'd get stuck in a situation where the Edge would keep trying to play back the old video stream, and not re-locate to the new location, unless all viewers gave up reconnecting. Losing an hour of the DVR is less of a concern to us than not being able to play any live video.

Hopefully this isn't a problem that will occur, but if there was a straight forward way to fix it, it would certainly build the robustness of the platform greatly. I'm just trying to avoid as many problems as possible

Once again, really appreciate you putting this module together. This has been a huge boon for me to putting together my streaming platform. You guys at Wowza rock.

All the best,

Matt

**Comment by rogerlittin** [comment]
We are looking to see if improvements can be made to the nDVR workflow in general to allow edges to use redundant origins. When this happens, we will looks to update this module to fully support nDVR.
